from .snake_game_node import NODE_CLASS_MAPPINGS as SNAKE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SNAKE_DISPLAY_MAPPINGS
from .flappy_bird_node import NODE_CLASS_MAPPINGS as FLAPPY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLAPPY_DISPLAY_MAPPINGS

# 合并两个节点的映射
NODE_CLASS_MAPPINGS = {**SNAKE_MAPPINGS, **FLAPPY_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**SNAKE_DISPLAY_MAPPINGS, **FLAPPY_DISPLAY_MAPPINGS}

WEB_DIRECTORY = "js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY'] 